sys-apps/nix: revert "add 2.25.0"
This reverts commit 7d9391925ba080aff03e8c9aa29dc31f13e66708.

`nix-2.25.0` does not build against latest release of libgit2 as

    src/libfetchers/git-utils.cc:288:13: error: ‘git_mempack_write_thin_pack’ was not declared in this scope.

It depends on unreleased `libgit2` feature: https://github.com/libgit2/libgit2/commit/f9c35fb50998d1c9d26293a18ade3d7c32f6ecb0