sys-apps/nix: add missing USE=s3 dependency on dev-libs/aws-sdk-cpp
Noticed and debugged by implr on `USE=s3 nix` setup:

```
$ nix ping-store --store 's3://BUCKET'
error: don't know how to open Nix store 's3://BUCKET'
```

While at it avoid automagic aws header detection and always use user's
USE=s3 preference. That way instead of installing nix with unexpected
missing feature it should break the build.

Reported-by: implr
Closes: https://github.com/trofi/nix-guix-gentoo/issues/12
Package-Manager: Portage-3.0.20, Repoman-3.0.3