sys-apps/busybox-nix-sandbox-shell: embed 'tar'/'mv' into busybox shell
'nix-channel --update' fails as:
```
$ nix-channel --update
unpacking channels...
warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels'
  does not exist, ignoring
/nix/store/ccm5fz10c5n4ch6z64flcgsqqdbm9bw8-unpack-channel.sh:
  line 1: mkdir: not found
builder for '/nix/store/6ijpvhx3fbn8qzn9f7in9fwiah8vr2b5
  -nixpkgs-20.09pre215033.ddc2f887f5f.drv' failed with exit code 127
error: build of '/nix/store/6ijpvhx3fbn8qzn9f7in9fwiah8vr2b5
  -nixpkgs-20.09pre215033.ddc2f887f5f.drv' failed
error: program '/usr/bin/nix-env' failed with exit code 100
```

Note: `busybox-nix-sandbox-shell` does not provide `mkdir` (and `tar`).
`nix`'s. The change enables there builtins.

Reported-and-fixed-by: pvgoran
Closes: https://github.com/trofi/nix-guix-gentoo/issues/5
Package-Manager: Portage-2.3.88, Repoman-2.3.20
Signed-off-by: Sergei Trofimovich <slyfox@gentoo.org>