generate-acct-user.bash: add nixbld and guixbuild /etc/group entries
In issues #21 Stinjul noticed that after migration from user.eclass
nix-daemon broke due to missing group entry:

    nix-channel --update
    error: the build users group 'nixbld' has no members

Reported-by: Stinjul
Fix-by: Stinjul
Closes: https://github.com/trofi/nix-guix-gentoo/issues/21