dev-scheme/guile-ssh: drop problematic musl patch
Without the change build on
    default/linux/amd64/17.1/systemd/clang/merged-usr
profile fails as:

    log.c:98:10: error: call to undeclared function 'backtrace'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
      size = backtrace (array, STACK_BUF_SZ);
             ^

It's caused by an invalid files/guile-ssh-0.16.0-musl.patch added in
    https://bugs.gentoo.org/877721

It removes `#include <execinfo.h>`. But that header's symbols are being
used in log.c.

Bug: https://bugs.gentoo.org/903689