sys-apps/lix: require at least linux-headers-6.7
Without the change the build fails on linux-headers-6.6 as:

    ../lix/src/libstore/platform/linux.cc:302:23: error: ‘__NR_futex_requeue’ was not declared in this scope

Issue: https://github.com/trofi/nix-guix-gentoo/issues/52